name: 'Build container Image'

on:
  workflow_dispatch:

env:
  IMAGE_NAME_TAG: example-app:${{ github.ref_name }}-${{ github.sha }}

permissions: read-all

jobs:
  image-build-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - name: 'Login to Docker Hub'
        run: |
          docker login -u "${DOCKERHUB_USERNAME}" -p "${DOCKERHUB_TOKEN}"
      - name: 'Build Docker image'
        run: |
          docker build -t "docker.io/${DOCKERHUB_USERNAME}/${{ env.IMAGE_NAME_TAG }}" .
      - name: 'Push Docker image'
        run: |
          docker push "docker.io/${DOCKERHUB_USERNAME}/${{ env.IMAGE_NAME_TAG }}"